
import React, { useRef } from 'react';
import { Modal } from '../Modal';

interface PrintModalProps {
    isOpen: boolean;
    onClose: () => void;
    svgContent: string;
    assemblyName: string;
}

export const PrintModal: React.FC<PrintModalProps> = ({ isOpen, onClose, svgContent, assemblyName }) => {
    const printRef = useRef<HTMLDivElement>(null);

    const handlePrint = () => {
        window.print();
    };

    return (
        <Modal
            isOpen={isOpen}
            onClose={onClose}
            onConfirm={handlePrint}
            title="Print Preview"
            confirmText="Print"
        >
            <div className="print-area-wrapper bg-gray-900 p-2 rounded-lg">
                <div id="print-area" ref={printRef} className="bg-white p-8 text-black">
                    <h1 className="text-xl font-bold mb-4">{assemblyName} - 2D Projection</h1>
                    <div dangerouslySetInnerHTML={{ __html: svgContent }} />
                    <p className="text-xs text-gray-500 mt-4">Generated by SynapseForge AI</p>
                </div>
            </div>
            <style>
                {`
                    @media print {
                        body * {
                            visibility: hidden;
                        }
                        #print-area, #print-area * {
                            visibility: visible;
                        }
                        #print-area {
                            position: absolute;
                            left: 0;
                            top: 0;
                            width: 100%;
                        }
                    }
                `}
            </style>
        </Modal>
    );
};
