import React, { useState } from 'react';

interface LegalGuardProps {
    onAccept: () => void;
}

export const LegalGuard: React.FC<LegalGuardProps> = ({ onAccept }) => {
    const [checks, setChecks] = useState({ tos: false, liability: false, ip: false });

    const allAccepted = checks.tos && checks.liability && checks.ip;

    return (
        <div className="fixed inset-0 z-[100] bg-brand-dark/95 backdrop-blur-xl flex items-center justify-center p-4 overflow-y-auto">
            <div className="max-w-2xl w-full bg-gray-900 border-2 border-brand-cyan/20 rounded-3xl p-8 shadow-[0_0_50px_rgba(0,255,255,0.1)] my-8">
                <h2 className="text-3xl font-black text-brand-light mb-2 tracking-tighter uppercase italic">Legal & Safety Protocols</h2>
                <p className="text-gray-500 mb-8 font-medium italic">Vault Initialization Agreement v2026.1</p>

                <div className="space-y-6 max-h-80 overflow-y-auto pr-4 mb-8 custom-scrollbar">
                    <div className="p-4 bg-red-900/10 border border-red-900/40 rounded-xl">
                        <h4 className="text-red-400 font-black text-[10px] uppercase tracking-widest mb-1 flex items-center gap-2">
                             <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2.5} stroke="currentColor" className="w-4 h-4"><path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z" /></svg>
                             Critical Engineering Liability Warning
                        </h4>
                        <p className="text-xs text-gray-400 leading-relaxed">
                            Calculations for structural integrity, material stability, and fluid dynamics generated by the Forge are strictly <strong>theoretical</strong>. 
                            Physical deployment without validation by a human Licensed Professional Engineer (PE) is at the user's sole risk. 
                            SynapseForge AI and CAIDI Institute provide no warranty for physical world safety.
                        </p>
                    </div>

                    <div className="space-y-5 text-sm text-gray-300">
                        <div>
                            <p className="font-black text-[10px] text-brand-cyan uppercase tracking-widest mb-1">1. Professional Limitation</p>
                            <p className="text-gray-400">CAIDI Institute is a research facilitator. We do not provide licensed engineering, medical, or legal counsel. The IP drafting module is an assistive tool, not a legal guarantee of USPTO registration.</p>
                        </div>
                        <div>
                            <p className="font-black text-[10px] text-brand-cyan uppercase tracking-widest mb-1">2. Data Sovereignty</p>
                            <p className="text-gray-400">Your engineering inputs and concept outputs are private to your tenant vault. We operate under a "Zero-Training" guarantee: your trade secrets are never used to train global generative models.</p>
                        </div>
                        <div>
                            <p className="font-black text-[10px] text-brand-cyan uppercase tracking-widest mb-1">3. Indemnification</p>
                            <p className="text-gray-400">By initializing this vault, you agree to indemnify and hold harmless Richard McWilliams and his affiliates from any claims arising from the manufacturing or use of prototypes designed within this environment.</p>
                        </div>
                    </div>
                </div>

                <div className="space-y-3">
                    <label className="flex items-center gap-3 p-4 bg-gray-800/40 rounded-xl border border-gray-700 cursor-pointer hover:border-brand-cyan transition-all group">
                        <input type="checkbox" className="w-5 h-5 accent-brand-cyan rounded border-gray-600 bg-gray-700" onChange={e => setChecks({...checks, tos: e.target.checked})} />
                        <div>
                            <span className="text-sm text-gray-300 font-bold block leading-none">Accept Master Service Agreement</span>
                            <span className="text-[10px] text-gray-500 uppercase tracking-tighter">Terms of Service & Global Privacy Policy</span>
                        </div>
                    </label>
                    <label className="flex items-center gap-3 p-4 bg-gray-800/40 rounded-xl border border-gray-700 cursor-pointer hover:border-red-500 transition-all group">
                        <input type="checkbox" className="w-5 h-5 accent-red-500 rounded border-gray-600 bg-gray-700" onChange={e => setChecks({...checks, liability: e.target.checked})} />
                        <div>
                            <span className="text-sm text-red-400 font-bold block leading-none">Accept Zero-Liability Clause</span>
                            <span className="text-[10px] text-gray-500 uppercase tracking-tighter">Theoretical output acknowledgement</span>
                        </div>
                    </label>
                    <label className="flex items-center gap-3 p-4 bg-gray-800/40 rounded-xl border border-gray-700 cursor-pointer hover:border-brand-cyan transition-all group">
                        <input type="checkbox" className="w-5 h-5 accent-brand-cyan rounded border-gray-600 bg-gray-700" onChange={e => setChecks({...checks, ip: e.target.checked})} />
                        <div>
                            <span className="text-sm text-gray-300 font-bold block leading-none">Acknowledge IP Sovereignty</span>
                            <span className="text-[10px] text-gray-500 uppercase tracking-tighter">Individual Attribution & Forge Ownership Rights</span>
                        </div>
                    </label>
                </div>

                <button 
                    disabled={!allAccepted}
                    onClick={onAccept}
                    className="w-full mt-8 py-4 bg-brand-cyan text-gray-900 font-black uppercase tracking-widest rounded-2xl hover:bg-cyan-400 transition-all shadow-xl shadow-cyan-900/20 active:scale-[0.98] disabled:opacity-10 disabled:grayscale"
                >
                    Initialize Sovereign Vault
                </button>
            </div>
            
            <style>{`
                .custom-scrollbar::-webkit-scrollbar { width: 4px; }
                .custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
                .custom-scrollbar::-webkit-scrollbar-thumb { background: #334155; border-radius: 10px; }
            `}</style>
        </div>
    );
};