import React, { useState } from 'react';

interface PartnerIndemnityModalProps {
  onSign: (signature: string) => void;
  onCancel: () => void;
}

export const PartnerIndemnityModal: React.FC<PartnerIndemnityModalProps> = ({ onSign, onCancel }) => {
  const [signature, setSignature] = useState('');

  return (
    <div className="fixed inset-0 z-[110] bg-gray-950/98 backdrop-blur-md flex items-center justify-center p-4 animate-fade-in">
      <div className="max-w-3xl w-full bg-black border border-brand-cyan/40 rounded-3xl p-10 shadow-cyan-900/40 shadow-2xl animate-scale-in">
        <div className="flex justify-between items-start mb-8">
          <div>
            <h2 className="text-3xl font-black text-brand-light tracking-tighter italic uppercase">Partner Protocol Initialization</h2>
            <p className="text-brand-cyan text-[10px] font-black uppercase tracking-[0.25em] mt-1">High-Risk Engineering Indemnity Sign-off</p>
          </div>
          <div className="text-right text-[10px] text-gray-500 font-mono">
            REF: SF-IND-2026-BETA
          </div>
        </div>

        <div className="bg-gray-900/50 p-6 rounded-xl border border-gray-800 text-sm text-gray-400 space-y-5 mb-8 max-h-72 overflow-y-auto custom-scrollbar leading-relaxed">
          <div>
            <h4 className="font-black text-white text-xs uppercase tracking-widest mb-1">1. Scope of Augmented Intelligence</h4>
            <p>Partner acknowledges that SynapseForge AI provides <strong>Augmented Intelligence</strong> outputs. These outputs are mathematical conjectures and conceptual frameworks. Richard McWilliams Consulting LLC does not warrant the physical world safety of any AI-derived design.</p>
          </div>
          
          <div>
            <h4 className="font-black text-white text-xs uppercase tracking-widest mb-1">2. Mandatory PE Verification</h4>
            <p>Partner warrants that all designs intended for physical deployment, fabrication, or testing will be reviewed and certified by a <strong>Licensed Professional Engineer (PE)</strong> independent of the CAIDI Institute. Partner waives any claim regarding the accuracy of G-Code, CAD files, or chemical formulations generated by the platform.</p>
          </div>

          <div>
             <h4 className="font-black text-white text-xs uppercase tracking-widest mb-1">3. Physical Liability Transfer</h4>
             <p>Partner assumes 100% liability for any physical testing, manufacturing, or wind-tunnel deployment of materials initiated within this environment. CAIDI Institute provides no warranty for structural integrity in non-simulated environments.</p>
          </div>
        </div>

        <div className="space-y-6">
          <div>
            <label className="block text-[10px] font-black text-gray-500 uppercase tracking-widest mb-2 ml-1">Type "I ACCEPT" followed by your Legal Identity to proceed</label>
            <input 
              type="text" 
              className="w-full p-4 bg-gray-900 border-2 border-gray-700 rounded-xl text-brand-cyan font-mono outline-none focus:border-brand-cyan transition-all shadow-inner uppercase"
              placeholder="I ACCEPT - [FULL NAME]"
              value={signature}
              onChange={(e) => setSignature(e.target.value.toUpperCase())}
            />
          </div>

          <div className="flex gap-4">
             <button 
                onClick={onCancel}
                className="px-8 py-4 text-xs font-black uppercase tracking-widest text-gray-500 hover:text-white transition-colors"
            >
                Cancel
            </button>
            <button 
                disabled={!signature.includes('I ACCEPT') || signature.length < 15}
                onClick={() => onSign(signature)}
                className="flex-1 py-4 bg-brand-cyan text-gray-900 font-black rounded-xl hover:bg-cyan-400 transition-all disabled:opacity-10 uppercase tracking-widest shadow-xl shadow-cyan-900/30 active:scale-95"
            >
                Activate Partner Layer Access
            </button>
          </div>
        </div>
      </div>
      <style>{`
        .custom-scrollbar::-webkit-scrollbar { width: 4px; }
        .custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
        .custom-scrollbar::-webkit-scrollbar-thumb { background: #334155; border-radius: 10px; }
      `}</style>
    </div>
  );
};